# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=70)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mutexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutexs', models.CharField(max_length=500)),
            ],
        ),
    ]
