# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email_address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
