# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutexapp', '0002_auto_20161203_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('visiting_time', models.DateTimeField()),
            ],
        ),
    ]
