# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutexapp', '0004_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
