# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutexapp', '0005_delete_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email_address',
            new_name='email',
        ),
    ]
